'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class AboutUsPage

    '''<summary>
    '''form1 control.
    '''</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

End Class
